version: '3'
services:
  logstash:
    image: logstash:7.6.0
    #    ports:
    #      - "4560:4560"
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - ./logstash.conf:/etc/logstash.conf
      - ./movie.cvs:/initialize/movie.cvs
    networks:
      - elasticsearch-net
    entrypoint:
      - logstash
      - -f
      - /etc/logstash.conf

networks:
  elasticsearch-net:
    driver: bridge

