version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.5
    container_name: cerebro
    restart: always
    ports:
      - "9001:9000"
    command:
      - -Dhosts.0.host=http://es01:9200
    networks:
      - es7net
  kibana:
    image: kibana:7.6.0
    container_name: kibana7
    restart: always
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - "5601:5601"
    networks:
      - es7net
  es01:
    image: yangbingdong/elasticsearch-ik-pinyin:7.6.0
    restart: always
    environment:
      - cluster.name=geektime
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es7net
  es02:
    image: yangbingdong/elasticsearch-ik-pinyin:7.6.0
    restart: always
    environment:
      - cluster.name=geektime
      - node.name=es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data2:/usr/share/elasticsearch/data
    networks:
      - es7net

volumes:
  es7data1:
    driver: local
  es7data2:
    driver: local

networks:
  es7net:
    driver: bridge
